service: higaidar

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${env:STAGE, "dev"}
  region: ap-northeast-1
  profile: ${self:service}-${self:provider.stage}-deploy
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rds-db:connect
      Resource:
        - "arn:aws:rds-db:${self:provider.region}:*:dbuser:${self:custom.rds.DBI_RESOURCE_ID}/lambda"
  environment:
    AWS_RDS_REGION: ${self:provider.region}
    AWS_RDS_HOST: ${self:custom.rds.HOST}
    AWS_RDS_PORT: ${self:custom.rds.PORT}
    AWS_RDS_USERNAME: ${self:custom.rds.USERNAME}
    AWS_RDS_DATABASE: ${self:custom.rds.DATABASE}

custom:
  env: ${file(../.env.${self:provider.stage}.yml)}
  rds: ${file(../.rake/rds/${self:service}-${self:provider.stage}/vars.yml)}

package:
  exclude:
    - .git/**
    - tmp/**
    - test/**
    - node_modules/.bin/**
    - node_modules/aws-sdk/**

functions:
  hello:
    handler: handler.hello
