default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("DB_PORT") { "3306" } %>

prod:
  <<: *default
  database: higaidar_prod

dev:
  <<: *default
  database: higaidar_dev

test:
  <<: *default
  database: higaidar_test
  
